name: 'whisper_scheme'
description: 'Openai library Whisper Library from whisper.cpp for recognition audio to text / speech to text without heavy gpu, support server side and client side.'
version: '0.0.0'
environment: 
  sdk: '^3.3.0'
dependencies:
  general_lib: ^0.0.34
  path: ^1.9.0
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.24.0'
repository: 'https://github.com/azkadev/whisper'
homepage: 'https://github.com/azkadev/general'
issue_tracker: 'https://github.com/azkadev/general/issues'
documentation: 'https://github.com/azkadev/whisper/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
