name: 'whisper_dart'
description: 'Openai library Whisper Library from whisper.cpp for recognition audio to text / speech to text without heavy gpu, support server side and client side.'
version: '0.0.0'
homepage: 'https://github.com/azkadev/general'
repository: 'https://github.com/azkadev/whisper'
issue_tracker: 'https://github.com/azkadev/general/issues'
documentation: 'https://github.com/azkadev/whisper/tree/main/docs'
publish_to: none
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null


environment: 
  sdk: '>=2.19.0 <3.0.0'
dev_dependencies: 
  lints: '^2.0.0'
  test: '^1.16.0'
dependencies: 
  ffi: '^2.0.1'
  ffmpeg_dart: '^0.0.0' 
  general_lib: ^0.0.34
  universal_io: '^2.2.0'
  whisper:
    path: ../whisper
  whisper_scheme:
    path: ../whisper_scheme
    