name: Build and Release Android arm
on: [push]
jobs:
  build:
    name: Build Apps
    runs-on: macos-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'
      - name: Open example
        run: |
          cd example
          flutter pub get
          # flutter build apk --debug --target-platform=android-arm64
          flutter build apk --release --target-platform=android-arm64
      # - name: Publish artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: App
      #     path: "example/build/app/outputs/apk/debug/*.apk"
      - name: Publish Release
        uses: marvinpinto/action-automatic-releases@latest
        with: 
          repo_token: "${{ github.token }}"
          automatic_release_tag: "latest-linux"
          prerelease: false
          title: "Development Build"
          files: |
            example/build/app/outputs/apk/release/*.apk 
 