name: Build and Release Android arm
on: [push]
jobs:
  build:
    name: Build Apps
    runs-on: macos-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.1'
          channel: 'stable'
      - name: Open example
        run:
          cd example
          flutter pub get
          flutter build apk --release --target-platform=android-arm64
      - name: Upload WSA
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: "./example/build/app/outputs/apk/release/*.apk"
